version: '3'
services:
  asyncio-play:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 50051:50051
    depends_on:
      - redis

  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

volumes:
  redis-data: