# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main", "devel" ]
  pull_request:
    branches: [ "main", "devel" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff pytest black tox
        if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
    - name: Check formatting + linting
      run: |
        tox -e check_formatting
    - name: Test with pytest
      run: |
        tox
    - name: Test against pre-release versions of dependencies
      run: |
        tox -e dev 
